use sh as default shell
ailohq/buildkite-utils pull request #6
Opened 2021-09-08 04:52 UTC by Smtih

node-alpine does not support `bash` shell.
I wonder if we should stick to `sh` as the default unless someone needs the extra power of `bash` explicitly for better compatibility.

2021-09-08 04:53 UTC, Smtih commented on lib/operators.ts
>      "-ec",
@micheal-hill could this somehow use the configured shell as well?

2021-09-08 22:17 UTC, micheal-hill requested changes

2021-09-08 22:17 UTC, micheal-hill commented on lib/operators.ts
>      "-ec",
This line is probably best to use `sh`, since that should be generally available. At this line we can't decide what shells are available.
We can use `$SHELL` to determine what shell we're _already in_, but it doesn't give anything when using `sh` and generally isn't useful until after the shell is already launched.

2021-09-08 22:17 UTC, micheal-hill commented on lib/operators.ts
> +  { delimiter = "EOF", stripMargin = true, shell = "sh -e" } = {},
Is it a big deal to explicitly pass `{ shell: 'sh -e' }` when bash is unavailable?
IIRC, only busybox-based images (eg. alpine) have this problem. Debian and other bases will work with `bash` without any trouble and are much easier to work with if you're writing scripts.

2021-09-17 05:43 UTC, Smtih commented on lib/operators.ts
> +  { delimiter = "EOF", stripMargin = true, shell = "sh -e" } = {},
Not really. the main issue was I had no access to the second one, I wonder if we should add a config

2021-09-17 05:44 UTC, Smtih commented on lib/operators.ts
>      "-ec",
This makes sense, should we be allowing someone to configure this, feel like that might be tricky. I think sticking with sh here should be enough.

2021-09-17 07:28 UTC, micheal-hill commented on lib/operators.ts
>      "-ec",
Yeah, keeping it as `sh` is probably good.

2021-09-17 07:29 UTC, micheal-hill approved these changes

2021-09-21 07:00 UTC, merged